/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "RentVsBuy": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "ServerApp": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}